FROM node:18-alpine

WORKDIR /usr/src/app
COPY package*.json ./

# RUN npm install
# COPY ./src ./src
# COPY ./public ./public
# CMD npm run start:dev
#? cache min nor wotking with this version of nodejs
# CMD npm config set cache-min 9999999 && \
CMD npm install && \
    npm run start:dev